/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotel.view.chambre;

import com.hotel.dao.PersonnelDAO;
import com.hotel.controller.AffectationController;
import javax.swing.*;
import java.awt.event.MouseEvent;
import com.hotel.model.Personnel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.Color;

/**
 *
 * @author LENOVO
 */
public class gestion_Personnel extends javax.swing.JPanel {

    /**
     * Creates new form gestion_Personnel
     */
     private Personnel persoCourant;
   private final AffectationController PersonnelController;
    JPopupMenu popup = new JPopupMenu();
    public boolean statuModif = false;
   
private JPopupMenu popup2 = new JPopupMenu();
private JMenuItem modifier;
private JMenuItem supprimer;
private JMenuItem supprimer2;

public gestion_Personnel() {
    initComponents();
    this.PersonnelController = new AffectationController();

    // Initialisation des items
    modifier = new JMenuItem("Modifier");
    supprimer = new JMenuItem("Supprimer");
    supprimer2 = new JMenuItem("Supprimer affectation");

    // Ajout des items aux menus
    popup.add(modifier);
    popup.add(supprimer);

    popup2.add(supprimer2);

    // Associer les actions
    modifier.addActionListener(this::modifierActionPerformed);
    supprimer.addActionListener(this::supprimerActionPerformed);
    supprimer2.addActionListener(this::supprimer2ActionPerformed);
}

    
    public void initDialog1()
    { 
      jTextField3.setText("Nom du Personnel/ ID du Personnel");
      jTextField4.setText("Chambre");
    }
    
    public void initDialog2()
    {
      nom.setText("Doe"); prenom.setText("Jones");role.setText("Entretien"); 
      telephone.setText("56566233"); adresse.setText("doejones@gmail.com");
    }
    
    public Personnel PersoCourant () { return persoCourant;}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jInternalFrame10 = new javax.swing.JInternalFrame();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        Search8 = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        jInternalFrame11 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Snap ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion du Personnel");
        jLabel1.setToolTipText("");

        jInternalFrame10.setVisible(true);

        jTable10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM & PRENOM", "ADRESSE", "ROLE", "Téléphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable10.setColumnSelectionAllowed(true);
        jTable10.getTableHeader().setReorderingAllowed(false);
        jTable10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable10MousePressed(evt);
            }
        });
        jScrollPane10.setViewportView(jTable10);

        jButton22.setText("+ Ajouter un Personnel");
        jButton22.addActionListener(this::jButton22ActionPerformed);

        jButton23.setText("Supprimer un Personnel");
        jButton23.addActionListener(this::jButton23ActionPerformed);

        Search8.setText("Search");
        Search8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Search8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Search8FocusLost(evt);
            }
        });

        jButton24.setText("Chercher");
        jButton24.addActionListener(this::jButton24ActionPerformed);

        javax.swing.GroupLayout jInternalFrame10Layout = new javax.swing.GroupLayout(jInternalFrame10.getContentPane());
        jInternalFrame10.getContentPane().setLayout(jInternalFrame10Layout);
        jInternalFrame10Layout.setHorizontalGroup(
            jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jInternalFrame10Layout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame10Layout.createSequentialGroup()
                        .addComponent(Search8, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame10Layout.setVerticalGroup(
            jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame10Layout.createSequentialGroup()
                .addGroup(jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane8.addTab("TABLEAU DE BORD", jInternalFrame10);

        jInternalFrame11.setVisible(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField2.setText("Search");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jButton25.setText("Chercher");

        jButton26.setText("Affectation");
        jButton26.addActionListener(this::jButton26ActionPerformed);

        javax.swing.GroupLayout jInternalFrame11Layout = new javax.swing.GroupLayout(jInternalFrame11.getContentPane());
        jInternalFrame11.getContentPane().setLayout(jInternalFrame11Layout);
        jInternalFrame11Layout.setHorizontalGroup(
            jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jInternalFrame11Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton25))
                    .addGroup(jInternalFrame11Layout.createSequentialGroup()
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame11Layout.setVerticalGroup(
            jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane8.addTab("AFFECTATION DE CHAMBRE", jInternalFrame11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable10MousePressed
        // TODO add your handling code here:
        if(evt.getButton() == MouseEvent.BUTTON3)
        { int row = jTable3.rowAtPoint(evt.getPoint());
            jTable3.setRowSelectionInterval(row, row);
            popup.show(jTable3, evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jTable10MousePressed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        PersonnelDAO.nbrPersonnel++;  // génération de ID
        initDialog2();
        ID.setText(String.valueOf(PersonnelDAO.nbrPersonnel));
        jDialog2.pack(); jDialog2.setVisible(true); jDialog2.setModal(true); jDialog2.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        int i  = jTable3.getSelectedRow();
        this.PersonnelController.deletePersonnel(Integer.parseInt(jTable3.getValueAt(i, 0).toString()));
        model.removeRow(i);
        String str = jTable3.getValueAt(i, 1).toString();
        model =  (DefaultTableModel)jTable1.getModel();
        for(int j =0; j < jTable1.getColumnCount(); i++)
        if(model.getColumnName(i).equals(str))
        { jTable1.remove(i); break;}
    }//GEN-LAST:event_jButton23ActionPerformed

    private void Search8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search8FocusGained
        // TODO add your handling code here:
        if(this.Search1.getText().equals("Search"))
        Search1.setText("");
        else
        {  String value = Search1.getText();
            for(int i =0; i < jTable3.getRowCount(); i++)
            {
                if(jTable3.getValueAt(i, 1).toString().contains(value)){
                    jTable3.setRowSelectionInterval(i, i);
                    /*for(int j = 0; j < jTable3.getColumnCount(); j++)*/  jTable3.scrollRectToVisible(jTable3.getCellRect(i, 0, true));
                    jTable3.setSelectionBackground(Color.GREEN);}
            }
        }
    }//GEN-LAST:event_Search8FocusGained

    private void Search8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search8FocusLost
        // TODO add your handling code here:
        if(Search1.getText().isEmpty())
        Search1.setText("Search");
    }//GEN-LAST:event_Search8FocusLost

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        String value = Search1.getText();
        for(int i = 0; i < jTable3.getRowCount(); i++)
        {
            if(jTable3.getValueAt(i, 1).toString().contains(value)){
                jTable3.setRowSelectionInterval(i, i);
                for(int j = 0; j < jTable3.getColumnCount(); j++)  jTable3.scrollRectToVisible(jTable3.getCellRect(i, 1, true));
                jTable3.changeSelection(i, 1, false, false);
                jTable3.setSelectionBackground(Color.GREEN);}
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        if(evt.getButton() == MouseEvent.BUTTON3)
        { int row = jTable1.rowAtPoint(evt.getPoint());
            jTable1.setRowSelectionInterval(row, row);
            popup2.show(jTable1, evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
        if(this.jTextField2.getText().equals("Search"))
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        if(jTextField2.getText().isEmpty())
        jTextField2.setText("Search");
    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        initDialog1();
        jDialog1.pack(); jDialog1.setVisible(true); jDialog1.setModal(true);
    }//GEN-LAST:event_jButton26ActionPerformed
    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        if(this.jTextField3.getText().equals("Nom du Personnel/ ID du Personnel"))
            jTextField3.setText("");
    }                                       

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
        if(this.jTextField4.getText().equals("Chambre"))
            jTextField4.setText("");
    }                                       

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
         if(jTextField4.getText().isEmpty())
            jTextField4.setText("Chambre");
    }                                     

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
         if(jTextField3.getText().isEmpty())
            jTextField3.setText("Nom du Personnel/ ID du Personnel");
    }                                     

    private void nomFocusLost(java.awt.event.FocusEvent evt) {                              
        // TODO add your handling code here:
         if(nom.getText().isEmpty())
            nom.setText("Doe");
    }                             

    private void prenomFocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
         if(prenom.getText().isEmpty())
            prenom.setText("Jones");
    }                                

    private void adresseFocusLost(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
         if(adresse.getText().isEmpty())
            adresse.setText("doejones@gmail.com");
    }                                 

    private void telephoneFocusLost(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
         if(telephone.getText().isEmpty())
            telephone.setText("56566233");
    }                                   

    private void roleFocusLost(java.awt.event.FocusEvent evt) {                               
        // TODO add your handling code here:
         if(role.getText().isEmpty())
            role.setText("Entretien");
    }                              

    private void IDFocusLost(java.awt.event.FocusEvent evt) {                             
        // TODO add your handling code here:
         if(ID.getText().isEmpty())
            ID.setText("102252");
    }                            

    private void nomFocusGained(java.awt.event.FocusEvent evt) {                                
        // TODO add your handling code here:
        if(this.nom.getText().equals("Doe"))
            nom.setText("");
    }                               

    private void prenomFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
        if(this.prenom.getText().equals("Jones"))
            prenom.setText("");
    }                                  

    private void adresseFocusGained(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        if(this.adresse.getText().equals("doejones@gmail.com"))
            adresse.setText("");
    }                                   

    private void telephoneFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
        if(this.telephone.getText().equals("56566233"))
            telephone.setText("");
    }                                     

    private void roleFocusGained(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
        if(this.role.getText().equals("Entretien"))
            role.setText("");
    }                                

    private void IDFocusGained(java.awt.event.FocusEvent evt) {                               
        // TODO add your handling code here:
        if(this.ID.getText().equals("102252"))
            ID.setText("");
    }                              

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        this.persoCourant = new Personnel(Integer.parseInt(ID.getText()), nom.getText(), prenom.getText(), Integer.parseInt(telephone.getText()), adresse.getText(), "", role.getText(), "");
        Object[] row = {persoCourant.getId(), persoCourant.getNom() + " " + persoCourant.getPrenom(), persoCourant.getAdress(), persoCourant.getRole(), telephone.getText()};
        jDialog2.dispose();
        if (this.statuModif) 
        { int ligne = jTable3.getSelectedRow();
            model.removeRow(ligne); this.statuModif = false;
         model.insertRow(ligne, row);
         this.PersonnelController.modifierInfo(persoCourant);
            
         return;
        }
        model = (DefaultTableModel)jTable3.getModel(); model.addRow(row);
        model = (DefaultTableModel)jTable1.getModel(); 
        model.addColumn(persoCourant.getNom() + " "+ persoCourant.getPrenom());
    
        this.PersonnelController.newPersonnel(persoCourant);
        
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if(!this.statuModif) PersonnelDAO.nbrPersonnel--;
        jDialog2.dispose();
    }                                        
      
    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
        String str = jTable3.getValueAt(row, 0).toString(); ID.setText(str);
        String[] str0 = jTable3.getValueAt(row, 1).toString().split(" ");
        nom.setText(str0[0]); prenom.setText(str0[1]);
        str = jTable3.getValueAt(row, 2).toString(); adresse.setText(str);
        str = jTable3.getValueAt(row, 3).toString(); role.setText(str);
        str = jTable3.getValueAt(row, 4).toString(); telephone.setText(str);
        this.statuModif = true;
        jDialog2.pack();jDialog2.setVisible(true); jDialog2.setModal(true); jDialog2.setLocationRelativeTo(null);
    }                                        

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        this.PersonnelController.deletePersonnel(Integer.parseInt(jTable3.getValueAt(row, 0).toString()));
        String str = jTable3.getValueAt(row, 1).toString();
        model.removeRow(row); 
        model =  (DefaultTableModel)jTable1.getModel();
        for(int i =0; i < jTable1.getColumnCount(); i++)
            if(model.getColumnName(i).equals(str))
            { 
                TableColumn column = jTable1.getColumn(model.getColumnName(i));
                jTable1.removeColumn(column); break;}
        
        
    }                                         

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String str1 = jTextField3.getText(); // Nom du personnel
        String str2 = jTextField4.getText(); // Chambre affectée
        int id = -1;  int i = 0;// Makeur
        jDialog1.dispose();
        
        for(i =0; i < jTable3.getRowCount(); i++)
            if (jTable3.getValueAt(i, 1).toString().contains(str1))
               {id = Integer.parseInt(jTable3.getValueAt(i, 0).toString()); break;}   
              
        if (id == -1)
          for(i =0; i < jTable3.getRowCount(); i++)
              if (jTable3.getValueAt(i, 0).toString().contains(str1))
                 {id = Integer.parseInt(jTable3.getValueAt(i, 0).toString()); break;}   
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object[] row = {};
        if(model.getRowCount()==0) 
        { model.addRow(row); model.setValueAt(str2 ,model.getRowCount()-1, i);
        return;}
       if(model.getRowCount() > this.PersonnelController.affectationNbr(id))
       {model.setValueAt(str2 ,this.PersonnelController.affectationNbr(id), i);}
       else
       {
        model.addRow(row); model.setValueAt(str2 ,model.getRowCount()-1, i);
        
       }
       
         
       this.PersonnelController.affectation(id, str2);
         
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jDialog1.dispose();
    }                                        

    private void supprimer2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); int id = 0;
        int column = jTable1.getSelectedColumn();
        String str = jTable1.getValueAt(row, column).toString();
        jTable1.setValueAt("", row, column);
        String str0 = jTable1.getColumnName(column);
        
        for(int i= 0; i < jTable3.getRowCount(); i++)
            if(jTable3.getValueAt(i, 1).equals(str0))
            { id = Integer.parseInt(jTable3.getValueAt(i, 0).toString()); break;}
        
        this.PersonnelController.desAffecter(id, str);
    }                                          

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        initDialog1();
        jDialog1.pack(); jDialog1.setVisible(true); jDialog1.setModal(true);
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String value = Search1.getText();
        for(int i = 0; i < jTable3.getRowCount(); i++)
        {
            if(jTable3.getValueAt(i, 1).toString().contains(value)){
                jTable3.setRowSelectionInterval(i, i);
                for(int j = 0; j < jTable3.getColumnCount(); j++)  jTable3.scrollRectToVisible(jTable3.getCellRect(i, 1, true));
                jTable3.changeSelection(i, 1, false, false);
                jTable3.setSelectionBackground(Color.GREEN);}
        }
    }                                        

    private void Search1FocusLost(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
        if(Search1.getText().isEmpty())
        Search1.setText("Search");
    }                                 

    private void Search1FocusGained(java.awt.event.FocusEvent evt) {                                    
        // TODO add your handling code here:
        if(this.Search1.getText().equals("Search"))
        Search1.setText("");
        else
        {  String value = Search1.getText();
            for(int i =0; i < jTable3.getRowCount(); i++)
            {
                if(jTable3.getValueAt(i, 1).toString().contains(value)){
                    jTable3.setRowSelectionInterval(i, i);
                    /*for(int j = 0; j < jTable3.getColumnCount(); j++)*/  jTable3.scrollRectToVisible(jTable3.getCellRect(i, 0, true));
                    jTable3.setSelectionBackground(Color.GREEN);}
            }
        }
    }                                   

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
        int i  = jTable3.getSelectedRow();
        this.PersonnelController.deletePersonnel(Integer.parseInt(jTable3.getValueAt(i, 0).toString()));
        model.removeRow(i);
        String str = jTable3.getValueAt(i, 1).toString();
        model =  (DefaultTableModel)jTable1.getModel();
        for(int j =0; j < jTable1.getColumnCount(); i++)
        if(model.getColumnName(i).equals(str))
        { jTable1.remove(i); break;}
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        PersonnelDAO.nbrPersonnel++;  // génération de ID
        initDialog2();
        ID.setText(String.valueOf(PersonnelDAO.nbrPersonnel));
        jDialog2.pack(); jDialog2.setVisible(true); jDialog2.setModal(true); jDialog2.setLocationRelativeTo(null);
    }                                        

    private void jTable3MousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if(evt.getButton() == MouseEvent.BUTTON3)
        { int row = jTable3.rowAtPoint(evt.getPoint());
            jTable3.setRowSelectionInterval(row, row);
            popup.show(jTable3, evt.getX(), evt.getY());

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //java.awt.EventQueue.invokeLater(new Runnable() {
        /*public void run() {
            new gestionPersonnel().setVisible(true);
        }*/
     //});
    }
    
    
    private javax.swing.JTextField ID;
    private javax.swing.JTextField adresse;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField role;
    private javax.swing.JTextField telephone;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search1;
    private javax.swing.JTextField Search2;
    private javax.swing.JTextField Search3;
    private javax.swing.JTextField Search4;
    private javax.swing.JTextField Search5;
    private javax.swing.JTextField Search6;
    private javax.swing.JTextField Search7;
    private javax.swing.JTextField Search8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JInternalFrame jInternalFrame10;
    private javax.swing.JInternalFrame jInternalFrame11;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JInternalFrame jInternalFrame8;
    private javax.swing.JInternalFrame jInternalFrame9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
