/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotel.view.reservation;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import com.hotel.model.Chambre;
import com.hotel.model.categorie;

import com.hotel.dao.ChambreDAO;
import java.sql.Connection;
import com.hotel.dao.ConnexionChambre;

/**
 *
 * @author LENOVO
 */
public class Reservation_Formulaire extends javax.swing.JPanel {

    /**
     * Creates new form Reservation_Formulaire
     */
    public Reservation_Formulaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        type = new javax.swing.JLabel();
        txt_type = new javax.swing.JComboBox<>();
        prix = new javax.swing.JLabel();
        txt_prix = new javax.swing.JTextField();
        Btn_Ajouter = new javax.swing.JButton();
        Btn_Annuler = new javax.swing.JButton();
        decrire = new javax.swing.JLabel();
        txt_decrire = new javax.swing.JTextField();
        txt_statut = new javax.swing.JLabel();
        txt_stt = new javax.swing.JTextField();
        clim = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*** Reservation de chambre ***");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        num.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        num.setForeground(new java.awt.Color(102, 102, 255));
        num.setText("N° chambre :");

        type.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        type.setForeground(new java.awt.Color(102, 102, 255));
        type.setText("Catégorie / Type : ");

        txt_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Confort / Supérieur", "Deluxe", "Suite" }));
        txt_type.addActionListener(this::txt_typeActionPerformed);

        prix.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        prix.setForeground(new java.awt.Color(102, 102, 255));
        prix.setText("Prix / nuit : ");

        Btn_Ajouter.setBackground(new java.awt.Color(153, 255, 153));
        Btn_Ajouter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Ajouter.setText("Ajouter");
        Btn_Ajouter.addActionListener(this::Btn_AjouterActionPerformed);

        Btn_Annuler.setBackground(new java.awt.Color(255, 102, 102));
        Btn_Annuler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Annuler.setText("Annuler");
        Btn_Annuler.addActionListener(this::Btn_AnnulerActionPerformed);

        decrire.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        decrire.setForeground(new java.awt.Color(102, 102, 255));
        decrire.setText("Description :");

        txt_statut.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txt_statut.setForeground(new java.awt.Color(102, 102, 255));
        txt_statut.setText("Statut :");

        clim.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        clim.setForeground(new java.awt.Color(102, 102, 255));
        clim.setText("Climatisation :");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("EstClimatisé");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Btn_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prix)
                            .addComponent(decrire)
                            .addComponent(txt_statut)
                            .addComponent(clim)
                            .addComponent(num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stt)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_type, 0, 485, Short.MAX_VALUE)
                            .addComponent(txt_prix)
                            .addComponent(txt_decrire)
                            .addComponent(txt_numero))))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(txt_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix)
                    .addComponent(txt_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decrire)
                    .addComponent(txt_decrire, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txt_statut)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_stt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clim)
                            .addComponent(jCheckBox1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_typeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_typeActionPerformed

    private void Btn_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AjouterActionPerformed
        // TODO add your handling code here:
        //Recupérer les champs de texte
        String numero = txt_numero.getText();
        String categorie = txt_type.getSelectedItem().toString();
        String prixParNuit = txt_prix.getText();
        String statut = txt_stt.getText();
        String description = txt_decrire.getText();
        boolean estClimatise = jCheckBox1.isSelected();

        //Créer l'objet chambre
        Chambre ch = new Chambre();
        ch.setnumero(Integer.parseInt(numero));
        ch.setcategorie(categorie);
        ch.setstatut(statut);
        ch.setprixParNuit(Double.parseDouble(prixParNuit));

        //Créer l'objet categorie
        categorie cat = new categorie();
        cat.setdescription(description);
        cat.setestClimatise(estClimatise);

        Connection con = ConnexionChambre.obtenirConnexion();
        if(con != null){
            // Appeler le dao pour sauvagarder chambre
            ChambreDAO dao = new ChambreDAO();
            dao.ajouterChambre(ch,cat);
            JOptionPane.showMessageDialog(this, "Enregistré avec succès");
            viderChamps();
        }else{
            JOptionPane.showMessageDialog(this, "Erreur : La base de donnée est fermée");
        }

    }//GEN-LAST:event_Btn_AjouterActionPerformed

    private void Btn_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AnnulerActionPerformed
        // TODO add your handling code here:
        viderChamps();
    }//GEN-LAST:event_Btn_AnnulerActionPerformed

public void viderChamps(){
            txt_numero.setText("");
            txt_prix.setText("");
            txt_stt.setText("");
            txt_decrire.setText("");
            txt_type.setSelectedIndex(0);
            jCheckBox1.setSelected(false);
            
            txt_numero.requestFocus();
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ajouter;
    private javax.swing.JButton Btn_Annuler;
    private javax.swing.JLabel clim;
    private javax.swing.JLabel decrire;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel num;
    private javax.swing.JLabel prix;
    private javax.swing.JTextField txt_decrire;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_prix;
    private javax.swing.JLabel txt_statut;
    private javax.swing.JTextField txt_stt;
    private javax.swing.JComboBox<String> txt_type;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
